routes/bbsContent.py
from routes import *
from utils import admin_required, log, login_required, current_user
from models.bbsContent import bbsContent
from models.bbsNode import bbsNode
from models.bbsComment import bbsComment
from models.bbsTag import bbsTag


main = Blueprint("bbs_content", __name__)


@main.route('/node/<int:id>')
def node_content(id):
    u = current_user()
    n = bbsNode.query.get(id)
    c = bbsContent.query.filter_by(node_id=id).order_by(bbsContent.create_time.desc()).all()
    return render_template('bbs/content_list.html', contents=c, u=u, node=n)


@main.route('/')
def content_show():
    u = current_user()
    c = bbsContent.query.order_by(bbsContent.create_time.desc()).all()
    return render_template('bbs/content_show.html', contents=c, u=u)


@main.route('/<int:id>')
def content_get(id):
    u = current_user()
    c = bbsContent.query.get(id)
    return render_template('bbs/content_get.html', content=c, u=u)


@main.route('/edit/all')
@login_required
def content_edit_all():
    u = current_user()
    c = bbsContent.query.all()
    return render_template('bbs/content_edit_all.html', contents=c, u=u)


@main.route('/edit/<int:id>')
@login_required
def content_edit(id):
    u = current_user()
    c = bbsContent.query.get(id)
    return render_template('bbs/content_edit.html', content=c, u=u)


@main.route('/add', methods=['POST'])
@login_required
def content_add():
    form = request.form
    c = bbsContent(form)
    c.add_node(form)
    c.gen_tags(form)
    c.draft = False
    c.save()
    return redirect(url_for('.content_show'))


@main.route('/delete/<int:id>')
@login_required
def content_delete(id):
    c = bbsContent.query.get(id)
    c.delete()
    return redirect(url_for('.content_show'))


@main.route('/update/<int:id>', methods=['POST'])
@login_required
def content_update(id):
    form = request.form
    c = bbsContent.query.get(id)
    c.update(form)
    c.save()
    return redirect(url_for('.content_show'))


@main.route('/update/node/<int:id>', methods=['POST'])
@login_required
def node_update(id):
    form = request.form
    c = bbsContent.query.get(id)
    c.add_node(form)
    c.save()
    return redirect(url_for('.content_show'))


@main.route('/update/tag/<int:id>', methods=['POST'])
@login_required
def tag_update(id):
    form = request.form
    c = bbsContent.query.get(id)
    c.gen_tags(form)
    c.save()
    return redirect(url_for('.content_show'))


@main.route('/remove/<int:id>', methods=['POST'])
@login_required
def tag_remove(id):
    form = request.form
    c = bbsContent.query.get(id)
    c.remove_tags(form)
    c.save()
    return redirect(url_for('.content_show'))


@main.route('/draft')
@login_required
def draft_show():
    u = current_user()
    t = bbsTag.query.all()
    n = bbsNode.query.all()
    return render_template('bbs/draft.html', nodes=n, tags=t, u=u)


@main.route('/draft/add', methods=['POST'])
@login_required
def draft_add():
    u = current_user()
    form = request.form
    c = bbsContent(form)
    c.add_node(form)
    c.gen_tags(form)
    c.user_id = u.id
    c.save()
    return redirect(url_for('.node_content', id=c.node_id))


@main.route('/comment/add', methods=['POST'])
@login_required
def add_comment():
    u = current_user()
    form = request.form
    c = bbsComment(form)
    c.author_id = u.id
    c.content_id = form.get('content_id', -1)
    c.save()
    return redirect(url_for('.content_get', id=c.content_id))

routes/user.py
from models.user import User
from routes import *
from utils import current_user, login_required,log

main = Blueprint('user', __name__)

Model = User


@main.route('/')
def index():
    u = current_user()
    if u is not None:
        return redirect('/weibo')
    return render_template('user/user_index.html', next=request.referrer)


@main.route('/logout')
@login_required
def logout():
    u = current_user()
    session.pop('uid')
    return redirect(url_for('.index'))


@main.route('/profile/change', methods=['POST'])
@login_required
def profile_change():
    form = request.form
    u = current_user()
    u.profile = form.get('profile','')
    u.save()
    return render_template('user/profile_change.html')


@main.route('/profile')
@login_required
def profile():
    u = current_user()
    return render_template('user/profile.html', u=u)

routes/weibo.py
from flask import Blueprint, render_template, redirect, request
from models.weibo import Weibo
from models.weiboComment import WeiboComment
from utils import current_user, login_required

main = Blueprint('weibo', __name__)


@main.route('/')
@login_required
def index():
    weibos = Weibo.query.order_by(Weibo.create_time.desc()).all()
    u = current_user()
    return render_template('/weibo/weibo.html', weibos=weibos, u=u)

templates/bbs/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bbs.css') }}">
    <link rel="stylesheet" href="/static/css/github-markdown.min.css">
    <link rel="stylesheet" href="/static/css/codemirror.css">
    <link rel="stylesheet" href="/static/css/material.css">
    {% block css %}{% endblock %}

    <script src="/static/js/jquery-3.1.0.min.js"></script>
    <script type="text/javascript" src="/static/js/codemirror.js"></script>
    <script type="text/javascript" src="/static/js/marked.min.js"></script>
    <script type="text/javascript" src="/static/js/python.js"></script>
    <script type="text/javascript" src="/static/js/renderMarkdown.js"></script>
    {% block script %}{% endblock %}
</head>
<body>
    <div class="bbs-top">
        <div class="bbs-header">
            <table class="bbs-header-table">
                <tbody>
                    <tr>
                        <td class="bbs-logo">
                            <a href="{{ url_for('bbs_content.content_show')}}"></a>
                        </td>
                        <td class="td-w40"></td>
                        <td class="bbs-global-nav">
                            <a class="bbs-glo-nav-link" href="{{ url_for('bbs_content.node_content', id=1) }}">技术</a>
                            <a class="bbs-glo-nav-link" href="{{ url_for('bbs_content.node_content', id=2)}}">生活</a>
                            <a class="bbs-glo-nav-link" href="{{ url_for('bbs_content.node_content', id=3)}}">娱乐</a>
                            <a class="bbs-glo-nav-link" href="{{ url_for('weibo.index') }}">小型微博</a>
                        </td>
                        <td class="bbs-user">
                            <a class="bbs-user-link" href="{{ url_for('user.index') }}">注册</a>
                            {% if u %}
                            <a class="bbs-user-link" href="{{ url_for('user.logout') }}">登出</a>
                            <a class="bbs-user-link" href="{{ url_for('user.profile') }}">个人</a>
                            {% else %}
                            <a class="bbs-user-link" href="{{ url_for('user.index') }}">登陆</a>
                            <a class="bbs-user-link" href="{{ url_for('user.index') }}">个人</a>
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="bbs-main">
        <div class="bbs-content">
        {% block main %}
        {% endblock %}
        </div>
    </div>

    <footer class="bbs-bottom">
        <div class="bbs-bottom-content">
            <div class="bbs-bottom-about">
                <a href="#">关于</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">FAQ</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">鸣谢</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="/">联系我</a>
            </div>
            <div class="bbs-bottom-info">
                -这是一个小小的论坛-<br>-Just for fun !-
            </div>
        </div>
    </footer>
</body>
</html>

templates/bbs/content_edit.html
{% extends "bbs/base.html" %}

{% block title %}
    技术博客
{% endblock %}
{% block script %}
    <script type="text/javascript" src="/static/js/renderMarkdown.js"></script>
    <script>
    var bindPreviewButton = function(){
        $('#id-preview').on("click",function(){
            var tag = $(".edit-content");
            log('this', this, 'tag', tag)
            var result = $("#box")
            var raw = tag.val();
            var data = marked(raw);
            var template = function(data){
                var t =
                `
                <div class="markdown-body">${data}</div>
                `
                return t;
            }
            result.html(template(data));
        })
    }
    $(document).ready(function(){
        renderMarkDown();
        bindPreviewButton();
    })
    </script>
{% endblock %}
{% block main %}
    <li class="col per-width">
        <div class="scroll">
            title : {{ content.title }}
            <br>
            create_time :{{ content.create_time }}
            <br>
            tags : {% for tag in content.tags %}
                    {{ tag.name }}
                    {% endfor %}
            <br>
            node : {{ content.node.name }}

            <form action="{{ url_for('.content_update', id=content.id) }}" method="post">
                <textarea name="title" class="edit-title">{{ content.title }}</textarea>
                <textarea name="content" class="edit-content">{{ content.content }}</textarea>
                <textarea name="node" class="edit-node"></textarea>
                <button>update-content</button>
            </form>
            <button id="id-preview">preview</button>
            <form action="{{ url_for('.tag_remove', id=content.id) }}" method="post">
                <textarea name="tag"></textarea>
                <button>remove-tag</button>
            </form>
            <form action="{{ url_for('.tag_update', id=content.id) }}" method="post">
                <textarea name="tag"></textarea>
                <button>update-tag</button>
            </form>
            <form action="{{ url_for('.node_update', id=content.id) }}" method="post">
                <textarea name="node" placeholder="node"></textarea>
                <button>update-node</button>
            </form>
            <form action="{{ url_for('.publish_content', id=content.id) }}">
                <button>publish</button>
            </form>
        </div>
    </li>
    <li class="col per-width">
        <div class="scroll">
            <div id="box"></div>
        </div>
    </li>
{% endblock %}

templates/bbs/content_edit_all.html
{% extends "bbs/base.html" %}

{% block title %}
    文章目录
{% endblock %}

{% block main %}
    <li class="col">
        {% for content in contents %}
        <div class="scroll">
            <a href="{{ url_for('.content_edit', id=content.id) }}">{{ content.title }}</a>
            <br>
            create_time :{{ content.create_time }}
            <br>
            tags : {% for tag in content.tags %}
                    {{ tag.name }}
                    {% endfor %}
            <br>
            node : {{ content.node.name }}
        </div>
        {% endfor %}
    </li>
{% endblock %}

templates/bbs/content_get.html
{% extends "bbs/base.html" %}

{% block title %}
    Just for fun!
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function(){
            renderMarkDown();
        })
    </script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/bbs_content.css">
{% endblock %}
{% block main %}
<div class="content-main wrapper">
    <div class="content-leftbar"></div>
    <div class="content-rightbar">
        <div class="height-50"></div>
        <div class="content-wrapper">
            您现在所在的位置是
            <strong>{{ content.node.name }}</strong>
            <br>
	{% if u %}
            <a href="{{ url_for('bbs_content.draft_show')}}">&nbsp;&nbsp;&nbsp;点击此处</a>
            <br>
            发表主题文章
	{% endif %}
        </div>
    </div>
    <div class="content-main-content">
        <div class="content-wrapper">
            <div class="content-container border-top">
                <div class="content-cell">
                    <div class="user-avatar">
                        <img src="{{ content.author.avatar_url}}">
                    </div>
                    <div class="content-box">
                        <div class="content-username">
                            <strong>{{ content.author.username }}</strong>
                            &nbsp;&nbsp;题主
                        </div>
                        <div class="content-title">
                            <span class="content-title-span box-title">
                                <a href="{{ url_for('.content_get', id=content.id) }}">{{ content.title }}</a>
                            </span>
                        </div>
                        <div class="content-body">
                            <div class="markdown-body">{{ content.content }}
                            </div>
                        </div>
                        <div class="content-description">
                            {% for tag in content.tags %}
                                 <div class="content-tag-decorate">
                                    <a href="#">{{ tag.name }}</a>
                                </div>
                            {% endfor %}
                            <div class="content-time fl-r">
                                发表于&nbsp;:&nbsp;{{ content.get_create_time() }}
                            </div>
                        </div>
                    </div>
                    <div class="height-50"></div>
                    <div class="comment-box border-top">
                        {% for c in content.comment %}
                        <div class="comment-cell border-top">
                            <div class="user-avatar">
				<img src="{{ content.author.avatar_url}}">
                            </div>
                            <div class="content-body">
                                <div class="content-username">
                                    <strong>{{ c.author.username }}</strong>
                                    <span> &nbsp;&nbsp;评论</span>
                                </div>
                                <div class="weibo-content-body comment">{{ c.comment }}</div>
                                <div class="content-time fl-r">
                                发表于&nbsp;:&nbsp;{{ c.get_create_time() }}
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="height-50"></div>
	{% if u %}
        <div class="content-edit-form border-top">
            <form action="{{  url_for('.add_comment')}}" method="post">
                <p>您可以在这里发表你的评论</p>
                <textarea name="comment" class="" placeholder="发表评论，评论长度不应小于1"></textarea>
                <input value="{{ content.id}}" name="content_id" type="hidden">
                <button class="btn-comment-add">发表评论</button>
            </form>
        </div>
	{% endif %}
    </div>
</div>
{% endblock %}

templates/bbs/content_list.html
{% extends "bbs/base.html" %}

{% block title %}
    技术博客
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/bbs_content.css">
{% endblock %}
{% block script %}
    
    <script>
        $(document).ready(function(){
            renderMarkDown();
        })
    </script>
{% endblock %}
{% block main %}
<div class="content-main wrapper">
    <div class="content-leftbar"></div>
    <div class="content-rightbar">
        <div class="height-50"></div>
        <div class="content-wrapper">
            您现在所在的位置是
            <strong>{{ node.name }}</strong>
            <br>
            <a href="{{ url_for('bbs_content.draft_show')}}">&nbsp;&nbsp;&nbsp;点击此处</a>
            <br>
            发表主题文章
        </div>
    </div>
    <div class="content-main-content">
        <div class="content-list content-wrapper">
            {% for content in contents %}
            <div class="content-container border-top">
                <div class="content-cell">
                    <div class="user-avatar">
                        <img src="{{ content.author.avatar_url}}">
                    </div>
                    <div class="content-body">
                        <div class="content-username">
                            <strong>{{ content.author.username }}</strong>
                        </div>
                         <div class="content-comment-info">
                            <span class="content-comment-num">
                                <a href="#">{{ content.comment.count() }}</a>
                            </span>
                        </div>
                        <div class="content-title">
                            <span class="content-title-span">
                                <a href="{{ url_for('.content_get', id=content.id) }}">{{ content.title }}</a>
                            </span>
                        </div>
                        <div class="content-description">
                            {% for tag in content.tags %}
                                 <div class="content-tag-decorate">
                                    <a href="#">{{ tag.name }}</a>
                                </div>
                            {% endfor %}
                            <div class="content-time fl-r">
                                发表于&nbsp;:&nbsp;{{ content.get_create_time() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>   
{% endblock %}

templates/bbs/content_show.html
{% extends "bbs/base.html" %}

{% block title %}
    Just for fun!
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/bbs_content.css">
{% endblock %}
{% block script %}
{% endblock %}
{% block main %}
<div class="content-main wrapper">
    <div class="content-leftbar"></div>
    <div class="content-rightbar">
        <div class="height-50"></div>
        <div class="content-wrapper">
            您现在所在的位置是
            <strong>首页</strong>
            <br>
            <a href="{{ url_for('bbs_content.draft_show')}}">&nbsp;&nbsp;&nbsp;点击此处</a>
            <br>
            发表主题文章
        </div>
    </div>
    <div class="content-main-content">
        <div class="content-list content-wrapper">
            {% for content in contents %}
            <div class="content-container border-top">
                <div class="content-cell">
                    <div class="user-avatar">
                        <img src="{{ content.author.avatar_url}}">
                    </div>
                    <div class="content-body">
                        <div class="content-node fl-r">
                            {{ content.node.name }}
                        </div>
                        <div class="content-username">
                            <strong>{{ content.author.username }}</strong>
                        </div>
                        <div class="content-comment-info">
                            <span class="content-comment-num">
                                <a href="#">{{ content.comment.count() }}</a>
                            </span>
                        </div>
                        <div class="content-title">
                            <span class="content-title-span">
                                <a href="{{ url_for('.content_get', id=content.id) }}">{{ content.title }}</a>
                            </span>
                        </div>
                        <div class="content-description">
                            {% for tag in content.tags %}
                                 <div class="content-tag-decorate">
                                    <a href="#">{{ tag.name }}</a>
                                </div>
                            {% endfor %}
                            <div class="content-time fl-r">
                                发表于&nbsp;:&nbsp;{{ content.get_create_time() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/bbs/draft.html
{% extends "bbs/base.html" %}

{% block title %}
    技术博客
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/bbs_content.css">
{% endblock %}
{% block script %}
    <script>
    var bindPreviewButton = function(){
        $('#id-preview').on("click",function(){
            var tag = $(".edit-content");
            var result = $("#box")
            var raw = tag.val();
            var data = marked(raw);
            var template = function(data){
                var t =
                `
                <div class="markdown-body">${data}</div>
                `
                return t;
            }
            result.html(template(data));
        })
    }
    $(document).ready(function(){
        renderMarkDown();
        bindPreviewButton();
    })
    </script>
{% endblock %}

{% block main %}
<div class="content-main wrapper">
    <div class="content-main-content">
        <div class="content-wrapper">
            <form action="{{ url_for('.draft_add') }}" method="post">
                <div class="indicate">标题处</div>
                <textarea class="content-title-edit" name="title" placeholder="title" required></textarea>
                <div class="indicate">文章处, 支持Markdown语法,亦可预览</div>
                <textarea class="edit-content" name="content" placeholder="content" required></textarea>
                <div class="indicate">类别&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;标签,可多选</div>
                <select name="node">
                    <option></option>
                    {% for node in nodes %}
                    <option value="{{ node.name }}">{{ node.name }}</option>
                    {% endfor %}
                </select>
                <select name="tag1">
                    <option></option>
                    {% for tag in tags %}
                    <option value="{{ tag.name }}">{{ tag.name }}</option>
                    {% endfor %}
                </select>
                <select name="tag2">
                    <option></option>
                    {% for tag in tags %}
                    <option value="{{ tag.name }}">{{ tag.name }}</option>
                    {% endfor %}
                </select>
                <div class="preview">
                    <button type="button" id="id-preview" class="fl-r">预览</button>
                </div>
                <button type="submit">添加文章</button>
            </form>
        </div>
        <div class="height-200"></div>
        <div id="box"></div>
    </div>
</div>
{% endblock %}

templates/bbs/node_list.html
{% extends "bbs/base.html" %}

{% block title %}
    添加目录
{% endblock %}

{% block main %}
    <li class="col">
        <div class="scroll">
            <form action="{{ url_for('.node_add') }}" method="post">
                <textarea name="name" placeholder="name"></textarea>
                <textarea name="description" placeholder="description"></textarea>
                <button>添加</button>
            </form>
        </div>
    </li>
    <li class="col">
        <div class="scroll">
            {% for node in nodes %}
            <br>
            name : {{ node.name }}
            <br>
            description : {{ node.description }}
            <br>
            content :
                {% for content in node.content %}
                {{ content.id }}
                {% endfor %}
            <br>
            tag :
                {% for tag in node.tags %}
                {{ tag.name }}
                {% endfor %}
            <br>
            <form action="{{ url_for('.node_delete', id=node.id) }}">
                <button>删除</button>
            </form>
            <form action="{{ url_for('.node_update', id=node.id) }}" method="post">
                <textarea placeholder="name" name="name"></textarea>
                <textarea placeholder="description" name="description"></textarea>
                <button>更新</button>
            </form>
            <br>
            {% endfor %}
        </div>
        <form action="{{ url_for('.node_add') }}" method="post">
            <textarea name="name" placeholder="name"></textarea>
            <textarea name="description" placeholder="description"></textarea>
            <button>添加</button>
        </form>
    </li>
{% endblock %}

templates/bbs/node_show.html
{% extends "bbs/base.html" %}

{% block title %}
    添加目录
{% endblock %}

{% block main %}
    <li class="col">
        <div class="scroll">
            <form action="{{ url_for('.node_add') }}" method="post">
                <textarea name="name" placeholder="name"></textarea>
                <textarea name="description" placeholder="description"></textarea>
                <button>添加</button>
            </form>
        </div>
    </li>
    <li class="col">
        <div class="scroll">
            name : {{ node.name }}
            <br>
            description : {{ node.description }}
            <br>
            content :
                {% for content in node.content %}
                {{ content.id }}
                {% endfor %}
            <br>
            tag :
                {% for tag in node.tags %}
                {{ tag.name }}
                {% endfor %}
            <br>
            <form action="{{ url_for('.node_delete', id=node.id) }}">
                <button>删除</button>
            </form>
            <form action="{{ url_for('.node_update', id=node.id) }}" method="post">
                <textarea placeholder="name" name="name"></textarea>
                <textarea placeholder="description" name="description"></textarea>
                <button>更新</button>
            </form>
            <br>
        </div>
        <form action="{{ url_for('.node_add') }}" method="post">
            <textarea name="name" placeholder="name"></textarea>
            <textarea name="description" placeholder="description"></textarea>
            <button>添加</button>
        </form>
    </li>
{% endblock %}

templates/bbs/tag_show.html
{% extends "bbs/base.html" %}

{% block title %}
    添加标签
{% endblock %}

{% block main %}
    <li class="col">
        <div class="scroll">
            <form action="{{ url_for('.tag_add') }}" method="post">
                <textarea name="name" placeholder="name"></textarea>
                <textarea name="node" placeholder="node"></textarea>
                <button>添加</button>
            </form>
        </div>
    </li>
    <li class="col">
        <div class="scroll">
            {% for tag in tags %}
            <br>
            tag : {{ tag.name }}
            <br>
            node_id : {{ tag.node_id }}
            <br>
            node : {{ tag.node.name }}
            <br>
            content :
                {% for content in tag.content %}
                {{ content.id }}
                {% endfor %}
            <br>
            <form action="{{ url_for('.tag_delete', id=tag.id) }}">
                <button>删除</button>
            </form>
            <form action="{{ url_for('.tag_update', id=tag.id) }}" method="post">
                <textarea placeholder="name" name="name"></textarea>
                <textarea placeholder="node" name="node"></textarea>
                <button>更新</button>
            </form>
            <br>
            {% endfor %}
        </div>
    </li>
{% endblock %}